parameters:
    database_host: localhost
    database_name: wy590204db
    database_user: wy590204
    database_password: 64011402
    database_prefix: IAD_
    server_url: http://54.149.37.27/
    firebase_url: https://ebid-release.firebaseio.com
    firebase_API: l2GdIeIHtaHzE9N9knb9VXHC003SO4pRURh8zcRK
    mail_host: smtp.163.com
    mail_port: 465
    mail_email: ebid2014@163.com
    mail_username: ebid2014@163.com
    mail_password: iadebid2014
    encryption: ssl
