parameters:
    database_host: localhost
    database_name: wy590204db
    database_user: wy590204
    database_password: 64011402
    database_prefix: IAD_
    firebase_url: https://ebid.firebaseio.com
    firebase_API: e5A8EV0jVok7il8goWmX5nQNX2VECH41UKmQvqIQ
