default:
    path:     /
    defaults: { _controller: 'ebid\Controller\testController::foo1Action' }

islogin:
    path:     /auth/islogin
    defaults: { _controller: 'ebid\Controller\AuthController::isloginAction' }
    
login:
    path:     /auth/login
    defaults: { _controller: 'ebid\Controller\AuthController::loginAction' }

logout:
    path:     /auth/logout
    defaults: { _controller: 'ebid\Controller\AuthController::logoutAction' }
        
admin:
    path:     /admin
    defaults: { _controller: 'ebid\Controller\adminController::indexAction'}

admin_success:
    path:     /admin/success
    defaults: { _controller: 'ebid\Controller\adminController::successAction'}
    
admin_logout:
    path:     /admin/logout
    defaults: { _controller: 'ebid\Controller\testController::foo1Action'}
    
ajax_autocomplete:
    path:     /ajax/autoCompleteProducts
    defaults: { _controller: 'ebid\Controller\AjaxController::autoCompleteProductsAction'}
    
register:
    path:     /user/register
    defaults: { _controller: 'ebid\Controller\UserController::registerAction'}
    methods:  ['POST']

upload:
    path:     /ajax/upload
    defaults: { _controller: 'ebid\Controller\AjaxController::uploadAction'}

uploadRemove:
    path:     /ajax/upload/remove
    defaults: { _controller: 'ebid\Controller\AjaxController::uploadRemoveAction'}

getCategory:
    path:     /ajax/getCategory
    defaults: { _controller: 'ebid\Controller\AjaxController::getCategoryAction'}


ProductAdd:
    path:     /product/add
    defaults: { _controller: 'ebid\Controller\ProductController::addAction'}